#pragma once

#pragma pack(push)
#pragma pack(1)
struct DATA
{
	enum {
	DIALOGUE_COUNT = 256,
	MAPSPRITE_COUNT = 0x10,
	SPRITE_COUNT = 0xD0,
	MAGIC_COUNT = 64,
	WEAPONMAGICGRAPHIC_COUNT = 28,
	AI_COUNT = 44,
	SHOP_COUNT = 70,
	BATTLE_COUNT = 0x80,
	BATTLEPATTERNTABLE_COUNT = 0x10,
	BACKDROP_COUNT = 16,
	ONTELEPORT_COUNT = 0x20,
	NNTELEPORT_COUNT = 0x40,
	NOTELEPORT_COUNT = 0x10,
	MAP_COUNT = 61,
	TREASURE_COUNT = 256,
	TILESET_COUNT = 8,
	MAPSPRITEGRAPHIC_COUNT = 0x1E,

	TEXTLABEL_SIZE = 30,
	WEAPONMAGICGRAPHICLABEL_SIZE = 20,
	AILABEL_SIZE = 20,
	SHOPLABEL_SIZE = 30,
	BATTLELABEL_SIZE = 30,
	BATTLEPATTERNTABLELABEL_SIZE = 40,
	BACKDROPLABEL_SIZE = 10,
	TELEPORTLABEL_SIZE = 30,
	MAPLABEL_SIZE = 20,
	TCLABEL_SIZE = 20,
	TILESETLABEL_SIZE = 10,
	SPRITELABEL_SIZE = 25,
	SPRITEGRAPHICLABEL_SIZE = 10,
	};

	char Header[4];  //DEVNOTE - this is here for convenience, it wasn't part of the struct in the original FFHackster source!
	char ROMPath[1000];
	bool TextViewInDTE[10];
	bool ShowLastClick;
	bool DrawDomainGrid;
	char TextLabels[DIALOGUE_COUNT][TEXTLABEL_SIZE + 1];
	char WepMagLabels[WEAPONMAGICGRAPHIC_COUNT][WEAPONMAGICGRAPHICLABEL_SIZE + 1];
	char AILabels[AI_COUNT][AILABEL_SIZE + 1];
	char ShopLabels[SHOP_COUNT][SHOPLABEL_SIZE + 1];
	char BattleLabels[BATTLE_COUNT][BATTLELABEL_SIZE + 1];
	char BattlePatternTableLabels[BATTLEPATTERNTABLE_COUNT][BATTLEPATTERNTABLELABEL_SIZE + 1];
	char BackdropLabels[BACKDROP_COUNT][BACKDROPLABEL_SIZE + 1];
	char ONTeleportLabels[ONTELEPORT_COUNT][TELEPORTLABEL_SIZE + 1];
	char NNTeleportLabels[NNTELEPORT_COUNT][TELEPORTLABEL_SIZE + 1];
	char NOTeleportLabels[NOTELEPORT_COUNT][TELEPORTLABEL_SIZE + 1];
	char TCLabels[TREASURE_COUNT][TCLABEL_SIZE + 1];
	char MapLabels[MAP_COUNT][MAPLABEL_SIZE + 1];
	char TilesetLabels[TILESET_COUNT][TILESETLABEL_SIZE + 1];
	char SpriteLabels[SPRITE_COUNT][SPRITELABEL_SIZE + 1];
	char SpriteGraphicLabels[MAPSPRITEGRAPHIC_COUNT][SPRITEGRAPHICLABEL_SIZE + 1];
	BYTE TintVariant;
	BYTE TintTiles[9][128];
	BYTE SmartTools[19][9];
};
#pragma pack(pop)
