//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FFHacksterEx.rc
//
#define IDD_FFHACKSTER_DIALOG           111
#define IDR_MAINFRAME                   112
#define IDD_EDIT_LABELS                 112
#define IDD_EDIT_VALUES                 113
#define IDD_ABOUT                       114
#define IDD_EDIT_RAM                    114
#define IDD_WELCOME                     115
#define IDD_DLG_NEWASM                  116
#define IDD_PROJECTSETTINGS             117
#define IDD_APPSETTINGS                 118
#define IDD_IMPORT                      122
#define IDPNG_GAMEPAD                   201
#define IDPNG_EDITOR                    202
#define IDPNG_SAVEDOWN                  203
#define IDPNG_LABEL                     204
#define IDPNG_SCREWRENCH                205
#define IDPNG_REVERT                    206
#define IDPNG_PUBLISH                   207
#define IDPNG_ADDFILESM                 209
#define IDPNG_EXPORT                    210
#define IDPNG_IMPORT                    211
#define IDPNG_CONTROLPANEL              212
#define IDPNG_EDITVALUES                213
#define IDPNG_RAMCHIP                   214
#define IDPNG_NEWPROJECT                215
#define IDPNG_FOLDERBLACK               216
#define IDPNG_FOLDERWHITE               217
#define IDPNG_OPENBLACKFOLDER           218
#define IDPNG_ARROWDOWN                 219
#define IDPNG_ARROWUP                   220
#define IDPNG_CLONESM                   221
#define IDPNG_UNZIP                     222
#define IDPNG_ZIP                       223
#define IDPNG_UNZIP24                   224
#define IDS_PROGRAMCAPTION              225
#define IDS_PROGRAMSUBTITLE             226
#define IDPNG_CLONE                     227
#define IDS_ASMDLL_DEFAULT              228
#define IDS_RELEASETEXT                 229
#define IDD_EDITORDIGEST2               230
#define IDD_DLG_NEWROM                  231
#define IDD_FOLDER_PREFS                232
#define IDC_PROJECTS_BTN_NEWROM         1663
#define IDC_PROJECTS_BTN_NEWASM         1664
#define IDC_PROJECTS_BTN_OPENROM        1665
#define IDC_FFH_BTN_IMPORTFFHDAT        1677
#define IDC_FFH_BTN_REVERT              1678
#define IDC_FFH_BTN_PUBLISH             1679
#define IDC_FFH_BTN_COMPILE             1680
#define IDC_NEWASM_BUTTON_PARENTFOLDER  1681
#define IDC_NEWASM_EDIT_PARENTFOLDER    1682
#define IDC_NEWASM_EDIT_PROJECTNAME     1683
#define IDC_NEWASM_EDIT_ZIPARCHIVE      1684
#define IDC_NEWASM_EDIT_PUBLISH         1685
#define IDC_NEWASM_CHECK_IMPORTDAT      1686
#define IDC_NEWASM_EDIT_DATFILE         1687
#define IDC_NEWASM_BUTTON_IMPORTDAT     1688
#define IDC_NEWASM_BUTTON_ZIPARCHIVE    1689
#define IDC_NEWASM_BUTTON_PUBLISH       1690
#define IDC_NEWASM_STATIC_ZIPARCHIVE    1691
#define IDC_PROJSET_STATIC_PROJTYPE     1700
#define IDC_PROJSET_BUTTON_REVERTPATH   1701
#define IDC_PROJSET_EDIT_REVERTPATH     1702
#define IDC_PROJSET_BUTTON_PUBLISHPATH  1703
#define IDC_APPSET_CHECK_PROMPTONCLOSE  1705
#define IDC_PROJECTS_STATIC_BANNER      1707
#define IDC_PROJSET_XFRAME_MOVEUP       1735
#define IDC_PROJECTS_BTN_EDITROM        1783
#define IDC_FFH_BTN_RUN                 1801
#define IDC_STATIC_EDITORDESC           1805
#define IDC_FRAME_CONTENT               1806
#define IDC_APPSETTINGS_BTN_RUNEXE      1809
#define IDC_APPSETTINGS_EDIT_RUNEXE     1810
#define IDC_FFH_BTN_VALUES              1824
#define IDC_FFH_BTN_RAM                 1825
#define IDC_FFH_BTN_APPSETTINGS         1826
#define IDC_FFH_BTN_MIN                 1827
#define IDC_FFH_BTN_LABELS              1829
#define IDC_FFH_BTN_PROJSETTINGS        1830
#define IDC_FFH_BTN_EDITORS             1831
#define IDC_ED_BTN_UP                   1834
#define IDC_ED_BTN_DOWN                 1835
#define IDC_ABOUT_STATIC_LABEL1         1844
#define IDC_ABOUT_STATIC_LABEL2         1845
#define IDC_ABOUT_STATIC_DETAIL1        1846
#define IDC_ABOUT_STATIC_DETAIL2        1847
#define IDC_ABOUT_STATIC_PD             1848
#define IDC_ABOUT_STATIC_RELEASE        1849
#define IDC_PROJSET_BUTTON_REVERTCLEAR  1852
#define IDC_APPSET_CHECK_PURGELOGONSTARTUP 1865
#define IDC_ABOUT_STATIC_LABEL3         1866
#define IDC_ABOUT_STATIC_DETAIL3        1867
#define IDC_APPSETTINGS_BTN_ADDLMODFOLDER 1868
#define IDC_APPSETTINGS_EDIT_ADDLMODFOLDER 1869
#define IDC_PROJECTS_BTN_UNZIP          1872
#define IDC_STATIC8                     1873
#define IDC_FFH_BTN_ARCHIVEPROJECT      1874
#define IDC_NEWASM_EDIT_ASMDLL          1885
#define IDC_ICONSTATIC                  1886
#define IDC_CHECK6                      1887
#define IDC_CHECK7                      1888
#define IDC_CHECK8                      1889
#define IDC_RADIO_LOCALHELP             1890
#define IDC_RADIO_WEBHELP               1891
#define IDC_BUTTON_LOCALHELP            1892
#define IDC_EDIT_LOCALHELP              1893
#define IDC_RADIO_HELP_IN_APPDIR        1894
#define IDC_MFCLINK1                    1895
#define IDC_MFCLINK_7ZIP                1895
#define IDC_MFCLINK2                    1896
#define IDC_MFCLINK_ICONMONSTR          1896
#define IDC_ABOUT_STATIC_PROGNAME       1897
#define IDC_MFCLINK3                    1898
#define IDC_COMBO_HELP_TYPES            1898
#define IDC_MFCLINK_FFH                 1898
#define IDC_PROJSTGS_CHECK_SUPPRESSASMWARNING 1899
#define IDC_MFCLINK_FFHPLUS             1899
#define IDC_PROJSTGS_BUTTON_COERCEASM   1900
#define IDC_MFCLINK_FFHPLUS2            1900
#define IDC_MFCLINK_FFGAMEFAQS          1900
#define IDC_APPSTGS_STATIC_HELPTYPE     1901
#define IDC_APPSTGS_STATIC_EXECTORUN    1902
#define IDC_APPSETTINGS_EDIT_PARAMS     1903
#define IDC_SYSLINK_PAULYGON            1904
#define IDC_SYSLINK_DISCH               1905
#define IDC_SYSLINK3                    1906
#define IDC_SYSLINK4                    1907
#define IDC_SYSLINK5                    1908
#define IDC_APPSETTINGS_BUTTON3_DIRECTORIES 1909
#define IDC_MFCPROPERTYGRID1            1915
#define IDC_MFCPROPGRID_FOLDERS         1915

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        235
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1916
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
